import 'dart:ui' show PlatformDispatcher;

import 'package:flutter/material.dart';
import 'app_settings.dart';

class AppStrings {
  const AppStrings._();

  static const Map<String, String> _zh = <String, String>{
    'allProjects': '所有專案',
    'projectMeta': '建立時間 {date} ・ 總頁數 {count}',
    'createProject': '新增專案',
    'enterProjectName': '輸入專案名稱',
    'cancel': '取消',
    'create': '建立',
    'page': '頁面',
    'template': '模板',
    'elements': '元素',
    'imageSource': '圖片來源',
    'imageSettings': '圖片設定',
    'imageSnap': '圖片吸附',
    'keepAtLeastOnePage': '至少保留一頁',
    'deletePage': '刪除頁面',
    'deleteProject': '刪除專案',
    'confirmDeleteCurrentPage': '確定要刪除目前頁面嗎？',
    'confirmDeleteCurrentProject': '確定要刪除這個專案嗎？',
    'imagePickerNotReady': '圖片選擇器尚未載入，請完整重啟 App 後再試一次。',
    'exportCanvasNotFound': '找不到可匯出的畫布',
    'canvasConvertFailed': '畫布轉換失敗',
    'imageDecodeFailed': '圖片解碼失敗',
    'exportedJpg': '已匯出 JPG：{path}',
    'exportFailedTryAgain': '匯出失敗，請再試一次。',
    'prepareExport': '準備匯出',
    'prepareImages': '準備圖片 {current}/{total}',
    'prepareImagesDone': '圖片準備完成',
    'renderPages': '正在合成頁面',
    'exportPageProgress': '匯出第 {current}/{total} 頁',
    'exportPageDone': '已完成 {current}/{total} 頁',
    'exportedToGallery': '已匯出到手機相簿',
    'partialExportFailed': '部分頁面匯出失敗',
    'saving': '儲存中',
    'saved': '已儲存',
    'pageIndicator': '第 {current} / {total} 頁',
    'fill': '填滿',
    'stackedImages': '上下雙圖',
    'image': '圖片',
    'text': '文字',
    'uploadPhoto': '上傳照片',
    'replaceImage': '更換圖片',
    'importImages': '匯入圖片',
    'originalSize': '原始尺寸',
    'snapToGuides': '位置吸附',
    'snapAll': '全部吸附',
    'snapPageEdges': '頁面邊界',
    'snapPageCenter': '頁面中心',
    'snapImageLines': '圖片軸線',
    'snapImageEdges': '圖片貼邊',
    'pageTitle': '第 {index} 頁',
    'attachedPhotos': '附帶 {count} 張照片',

    // New localization keys
    'settingsTitle': '設定',
    'appTagline': '輕鬆製作貼文',
    'themeColor': '主題色調',
    'extensions': '擴充功能',
    'aiCollaboration': 'AI 協作',
    'aiCollaborationSubtitleActive': '演算法交織的視覺交響，為你的排版尋找最完美的敘事順序。',
    'aiCollaborationSubtitleInactive': '打破常規，用智慧啟發靈感。請先驗證 Gemini API 金鑰。',
    'versionUpdate': '版本與更新',
    'updateAvailable': '目前 {version}，可更新到 {latest}',
    'currentVersion': '目前版本 {version}',
    'goToUpdate': '前往更新',
    'checking': '檢查中',
    'checkUpdates': '檢查更新',
    'geminiApiKey': 'Gemini API Key',
    'saveApiKey': '儲存 API Key',
    'aiUsageEstimate': 'AI 用量與費用估算',
    'estimatedCost': '預估花費：\${cost} USD',
    'reset': '重設',
    'settingsSaved': '設定已儲存',
    'enterApiKeyFirst': '請先輸入 Gemini API Key',
    'aiCollaborationEnabled': 'AI 協作已啟用',
    'apiUnavailable': 'API 無法使用，AI 協作無法啟用',
    'alreadyLatestVersion': '目前已是最新版本',
    'updateCheckFailed': '檢查更新失敗，請稍後再試',
    'networkError': '網路連線錯誤',
    'newVersionFound': '發現新版本',
    'updatePrompt': '最新版本為 v{version}，是否前往下載更新？',
    'askMeLater': '稍後再說',
    'downloadNow': '前往下載',
    'unnamedProject': '未命名專案',
    'enableAiFirst': '請先到設定啟用 AI 並驗證 API Key',
    'aiCreatedProject': 'AI 建立專案',
    'aiCreatingProject': 'AI 建立專案中...',
    'aiProjectCreationFailed': 'AI 建立專案失敗，請確認網路或 API Key 後再試',
    'preselectedPhotos': '預選照片',
    'selectPhotosOptional': '選擇要排版的照片 (非必選)',
    'createByAi': '由 AI 建立',
    'imagePosition': '圖片位置',
    'textPosition': '文字位置',
    'changePageRatio': '變更頁面比例',
    'changeRatioWarning': '目前專案已有內容，變更頁面比例可能會讓圖片位置或大小看起來位移。要繼續嗎？',
    'continueLabel': '繼續',
    'editText': '編輯文字',
    'applyTemplate': '套用模板',
    'applyTemplateWarning': '目前頁面已有內容，套用模板會清空原有圖片與文字。確定要清空並套用嗎？',
    'clearAndApply': '清空套用',
    'done': '完成',
    'nudgePosition': '位置微調',
    'crop': '裁切',
    'size': '大小',
    'textColor': '文字顏色',
    'imageCornerRadius': '圖片圓角',
    'hdrBrightness': 'HDR 亮度',
    'sdrToHdrBrightness': 'SDR→HDR',
    'deepAdjust': '深度調整',
    'adjBrightness': '亮度',
    'adjContrast': '對比',
    'adjSaturation': '飽和度',
    'adjHighlights': '亮部',
    'adjShadows': '暗部',
    'adjTemperature': '色溫',
    'adjTint': '色調',
    'hdrViewOn': 'HDR 檢視:開',
    'hdrViewOff': 'HDR 檢視:關',
    'edit': '編輯',
    'aiSortFailed': 'AI 排序失敗，請確認 API Key 或稍後再試',
    'aiSortSuggestion': 'AI 建議排序',
    'currentOrder': '目前順序',
    'suggestedOrder': '建議順序',
    'accept': '接受',
    'languageSetting': '語言設定',
    'languageFollowSystem': '跟隨系統',
    'languageTraditionalChinese': '繁體中文',
    'languageEnglish': 'English',
    'languageChangeNotice': '變更語言後將會立即套用。',
    'layers': '圖層',

    // Ultra HDR
    'hdrSectionTitle': 'Ultra HDR',
    'hdrSettingTitle': 'HDR 顯示與匯出',
    'hdrSettingSubtitle':
        '在支援的裝置上以 HDR 顯示與匯出 Ultra HDR 照片（Android 14+）。關閉後一律以 SDR 處理。',
    'hdrUnsupported': '此裝置不支援 Ultra HDR（需 Android 14 以上）',
    'hdrExportToggle': 'Ultra HDR 匯出',
    'sdrTreatmentLabel': 'SDR 圖片處理',
    'sdrNeutralLabel': '中性',
    'sdrNeutralDetail': '保持原樣',
    'sdrEnhancedLabel': '增強',
    'sdrEnhancedDetail': '提亮高光',
    'qualityOriginalLabel': '原始',
    'qualityOriginalDetail': '無損',
    'losslessQualityHint':
        '單張滿版未裁切的頁面會直接複製原始檔（0 重新編碼，HDR/EXIF 完整保留）；其他頁面以 2.4K 高品質重新渲染。',
    'losslessFallbackNotice': '{count} 頁不符合無損直出條件，已以 2.4K 重新渲染',
    'noLayers': '目前頁面沒有圖層',
  };

  static const Map<String, String> _en = <String, String>{
    'allProjects': 'All Projects',
    'projectMeta': 'Created {date} · {count} pages',
    'createProject': 'Create Project',
    'enterProjectName': 'Enter project name',
    'cancel': 'Cancel',
    'create': 'Create',
    'page': 'Page',
    'template': 'Template',
    'elements': 'Elements',
    'imageSource': 'Image Source',
    'imageSettings': 'Image Settings',
    'imageSnap': 'Snap',
    'keepAtLeastOnePage': 'Keep at least one page',
    'deletePage': 'Delete Page',
    'deleteProject': 'Delete Project',
    'confirmDeleteCurrentPage': 'Delete the current page?',
    'confirmDeleteCurrentProject': 'Delete this project?',
    'imagePickerNotReady':
        'The image picker is not ready yet. Please fully restart the app and try again.',
    'exportCanvasNotFound': 'Export canvas not found',
    'canvasConvertFailed': 'Canvas conversion failed',
    'imageDecodeFailed': 'Image decode failed',
    'exportedJpg': 'Exported JPG: {path}',
    'exportFailedTryAgain': 'Export failed. Please try again.',
    'prepareExport': 'Preparing export',
    'prepareImages': 'Preparing images {current}/{total}',
    'prepareImagesDone': 'Images ready',
    'renderPages': 'Rendering pages',
    'exportPageProgress': 'Exporting page {current}/{total}',
    'exportPageDone': 'Completed {current}/{total}',
    'exportedToGallery': 'Exported to gallery',
    'partialExportFailed': 'Some pages failed to export',
    'saving': 'Saving',
    'saved': 'Saved',
    'pageIndicator': 'Page {current} / {total}',
    'fill': 'Fill',
    'stackedImages': 'Top & Bottom',
    'image': 'Image',
    'text': 'Text',
    'uploadPhoto': 'Upload Photo',
    'replaceImage': 'Replace Image',
    'importImages': 'Import Images',
    'originalSize': 'Original Size',
    'snapToGuides': 'Snap',
    'snapAll': 'All Snap',
    'snapPageEdges': 'Page Edges',
    'snapPageCenter': 'Page Center',
    'snapImageLines': 'Image Lines',
    'snapImageEdges': 'Image Edges',
    'pageTitle': 'Page {index}',
    'attachedPhotos': '{count} attached photos',

    // New localization keys
    'settingsTitle': 'Settings',
    'appTagline': 'Easily create posts',
    'themeColor': 'Theme Color',
    'extensions': 'Extensions',
    'aiCollaboration': 'AI Collaboration',
    'aiCollaborationSubtitleActive':
        'An algorithmic visual symphony, seeking the perfect narrative order for your layout.',
    'aiCollaborationSubtitleInactive':
        'Break conventions and inspire with intelligence. Please verify your Gemini API key first.',
    'versionUpdate': 'Version & Updates',
    'updateAvailable': 'Current {version}, update available to {latest}',
    'currentVersion': 'Current version {version}',
    'goToUpdate': 'Go to Update',
    'checking': 'Checking',
    'checkUpdates': 'Check for Updates',
    'geminiApiKey': 'Gemini API Key',
    'saveApiKey': 'Save API Key',
    'aiUsageEstimate': 'AI Usage & Cost Estimate',
    'estimatedCost': 'Estimated cost: \${cost} USD',
    'reset': 'Reset',
    'settingsSaved': 'Settings saved',
    'enterApiKeyFirst': 'Please enter Gemini API Key first',
    'aiCollaborationEnabled': 'AI Collaboration enabled',
    'apiUnavailable': 'API not available, AI Collaboration cannot be enabled',
    'alreadyLatestVersion': 'Already the latest version',
    'updateCheckFailed': 'Update check failed, please try again later',
    'networkError': 'Network connection error',
    'newVersionFound': 'New Version Found',
    'updatePrompt': 'Latest version is v{version}. Go to download page?',
    'askMeLater': 'Ask Me Later',
    'downloadNow': 'Download Now',
    'unnamedProject': 'Unnamed Project',
    'enableAiFirst':
        'Please go to Settings to enable AI and verify API Key first',
    'aiCreatedProject': 'AI Created Project',
    'aiCreatingProject': 'AI creating project...',
    'aiProjectCreationFailed':
        'AI project creation failed. Please check your network or API Key and try again.',
    'preselectedPhotos': 'Pre-selected Photos',
    'selectPhotosOptional': 'Select photos for layout (optional)',
    'createByAi': 'Create by AI',
    'imagePosition': 'Image Position',
    'textPosition': 'Text Position',
    'changePageRatio': 'Change Page Ratio',
    'changeRatioWarning':
        'The current project already has content, changing the page ratio might cause image positions or sizes to shift. Continue?',
    'continueLabel': 'Continue',
    'editText': 'Edit Text',
    'applyTemplate': 'Apply Template',
    'applyTemplateWarning':
        'The current page already has content, applying the template will clear existing images and text. Clear and apply?',
    'clearAndApply': 'Clear & Apply',
    'done': 'Done',
    'nudgePosition': 'Nudge Position',
    'crop': 'Crop',
    'size': 'Size',
    'textColor': 'Text Color',
    'imageCornerRadius': 'Corner Radius',
    'hdrBrightness': 'HDR Brightness',
    'sdrToHdrBrightness': 'SDR→HDR',
    'deepAdjust': 'Adjust',
    'adjBrightness': 'Brightness',
    'adjContrast': 'Contrast',
    'adjSaturation': 'Saturation',
    'adjHighlights': 'Highlights',
    'adjShadows': 'Shadows',
    'adjTemperature': 'Temp',
    'adjTint': 'Tint',
    'hdrViewOn': 'HDR view: on',
    'hdrViewOff': 'HDR view: off',
    'edit': 'Edit',
    'aiSortFailed':
        'AI sorting failed, please check API Key or try again later',
    'aiSortSuggestion': 'AI Suggested Order',
    'currentOrder': 'Current Order',
    'suggestedOrder': 'Suggested Order',
    'accept': 'Accept',
    'languageSetting': 'Language Settings',
    'languageFollowSystem': 'Follow System',
    'languageTraditionalChinese': '繁體中文',
    'languageEnglish': 'English',
    'languageChangeNotice': 'Language changes will be applied immediately.',
    'layers': 'Layers',

    // Ultra HDR
    'hdrSectionTitle': 'Ultra HDR',
    'hdrSettingTitle': 'HDR display & export',
    'hdrSettingSubtitle':
        'Show and export Ultra HDR photos with real HDR on supported devices (Android 14+). When off, everything stays SDR.',
    'hdrUnsupported': 'This device does not support Ultra HDR (requires Android 14+).',
    'hdrExportToggle': 'Ultra HDR export',
    'sdrTreatmentLabel': 'SDR images',
    'sdrNeutralLabel': 'Neutral',
    'sdrNeutralDetail': 'as-is',
    'sdrEnhancedLabel': 'Enhanced',
    'sdrEnhancedDetail': 'boost highlights',
    'qualityOriginalLabel': 'Original',
    'qualityOriginalDetail': 'lossless',
    'losslessQualityHint':
        'Pages that are a single full-bleed, uncropped photo are copied byte-for-byte (no re-encode, HDR/EXIF preserved); other pages re-render at 2.4K.',
    'losslessFallbackNotice':
        '{count} page(s) did not qualify for lossless passthrough and were re-rendered at 2.4K',
    'noLayers': 'No layers on this page',
  };

  static AppStrings of(BuildContext context) {
    return const AppStrings._();
  }

  static AppStrings get system {
    return const AppStrings._();
  }

  String t(String key, {Map<String, String> args = const <String, String>{}}) {
    final language = AppSettingsController.instance.language;
    String targetLang;
    if (language == 'system') {
      final systemLang = PlatformDispatcher.instance.locale.languageCode
          .toLowerCase();
      if (systemLang.startsWith('zh')) {
        targetLang = 'zh';
      } else {
        targetLang = 'en';
      }
    } else {
      targetLang = language;
    }

    final map = (targetLang == 'zh') ? _zh : _en;
    var value = map[key] ?? key;
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }
}
